version: '3'
services:
    app:
        container_name: backend_chat
        environment:
            - DATABASE_URL=mongodb://mongo/tsnode
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "33356:33356"
        depends_on: 
            - mongo
        volumes:
            - .:/app
            - /app/node_modules
    mongo:
        container_name: mongo
        image: mongo